version: "3.9"

services:
  backend:
    build: .
    container_name: adoptme-backend
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - mongo
    volumes:
      - .:/app
    command: npm start

  mongo:
    image: mongo:6.0
    container_name: adoptme-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
